// AUTOGENERATED - DO NOT MODIFY
import Home from '../src/views/Home';import Customers from '../src/views/Customers';import CustomerDetails from '../src/views/CustomerDetails';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2025-12-29 19:18:59.5130915 -0300 -03 m=+7.061321401';

export { 
  Home,	

  Customers,	

  CustomerDetails	
 };

export default {
  "connect_permissions": null,
  "icon": "",
  "id": "com.portyo.portyo",
  "name": "Portyo",
  "permissions": [],
  "ui_extension": {
    "content_security_policy": {
      "connect-src": null,
      "image-src": null,
      "purpose": ""
    },
    "views": [
      {
        "component": "Home",
        "viewport": "stripe.dashboard.home.overview"
      },
      {
        "component": "Customers",
        "viewport": "stripe.dashboard.customer.list"
      },
      {
        "component": "CustomerDetails",
        "viewport": "stripe.dashboard.customer.detail"
      }
    ]
  },
  "version": "0.0.1"
};
