import { BaseType } from "./base.type";
import { UserType } from "./user.type";

export type Bio = BaseType & {
    sufix:string;
    clicks:number;
    views:number;
    user:UserType | string;
    blocks?: any[];
    html?: string;
    seoTitle?: string;
    seoDescription?: string;
    favicon?: string;
    googleAnalyticsId?: string;
    facebookPixelId?: string;
    seoKeywords?: string;
    ogTitle?: string;
    ogDescription?: string;
    ogImage?: string;
    noIndex?: boolean;
    bgType?: string;
    bgColor?: string;
    bgSecondaryColor?: string;
    bgImage?: string | null;
    bgVideo?: string | null;
    usernameColor?: string;
    imageStyle?: string;
    cardStyle?: string;
    cardBackgroundColor?: string;
    cardOpacity?: number;
    cardBlur?: number;
    cardBorderColor?: string;
    cardBorderWidth?: number;
    cardBorderRadius?: number;
    cardShadow?: string;
    cardPadding?: number;
    maxWidth?: number;
    font?: string;
    customFontUrl?: string | null;
    customFontName?: string | null;
    enableParallax?: boolean;
    parallaxIntensity?: number;
    parallaxDepth?: number;
    parallaxAxis?: string;
    parallaxLayers?: any[];
    floatingElements?: boolean;
    floatingElementsType?: string;
    floatingElementsColor?: string;
    floatingElementsDensity?: number;
    floatingElementsSize?: number;
    floatingElementsSpeed?: number;
    floatingElementsOpacity?: number;
    floatingElementsBlur?: number;
    enableSubscribeButton?: boolean;
    removeBranding?: boolean;
    customDomain?: string;
    integrations:any[]
}