import { Column, Entity, ManyToOne, JoinColumn, OneToMany } from "typeorm";
import { BaseEntity } from "./base-entity";
import { UserEntity } from "./user-entity";
import { BioEntity } from "./bio-entity";
import { AutoPostLogEntity } from "./auto-post-log-entity";

export type PostFrequency = "daily" | "weekly" | "biweekly" | "monthly";

@Entity()
export class AutoPostScheduleEntity extends BaseEntity {
    @Column({ type: "uuid" })
    bioId!: string;

    @ManyToOne(() => BioEntity, (bio) => bio.autoPostSchedules, { onDelete: "CASCADE" })
    @JoinColumn({ name: "bioId" })
    bio!: BioEntity;

    @Column({ type: "uuid" })
    userId!: string;

    @ManyToOne(() => UserEntity, (user) => user.autoPostSchedules, { onDelete: "CASCADE" })
    @JoinColumn({ name: "userId" })
    user!: UserEntity;

    @Column({ type: "boolean", default: true })
    isActive!: boolean;

    // Frequency: daily, weekly, biweekly, monthly
    @Column({ type: "varchar", default: "weekly" })
    frequency!: PostFrequency;

    // Topics/themes the user wants to write about
    @Column({ type: "text", nullable: true })
    topics!: string | null;

    // Keywords for SEO
    @Column({ type: "simple-array", nullable: true })
    keywords!: string[] | null;

    // Target audience description
    @Column({ type: "text", nullable: true })
    targetAudience!: string | null;

    // Tone of voice: professional, casual, friendly, etc.
    @Column({ type: "varchar", default: "professional" })
    tone!: string;

    // Preferred post length: short, medium, long
    @Column({ type: "varchar", default: "medium" })
    postLength!: string;

    // Language preference (auto-detect from bio if not set)
    @Column({ type: "varchar", nullable: true })
    language!: string | null;

    // Next scheduled post date
    @Column({ type: "timestamp", nullable: true })
    nextPostDate!: Date | null;

    // Last post date
    @Column({ type: "timestamp", nullable: true })
    lastPostDate!: Date | null;

    // Posts generated this month
    @Column({ type: "int", default: 0 })
    postsThisMonth!: number;

    // Month/year for tracking (format: "YYYY-MM")
    @Column({ type: "varchar", nullable: true })
    currentMonth!: string | null;

    // Summary of the bio generated by AI
    @Column({ type: "text", nullable: true })
    bioSummary!: string | null;

    // When the bio summary was generated
    @Column({ type: "timestamp", nullable: true })
    bioSummaryGeneratedAt!: Date | null;

    // Preferred time for posting (format: "HH:mm", e.g., "09:00", "14:30")
    @Column({ type: "varchar", length: 5, default: "09:00" })
    preferredTime!: string;

    // When the schedule should start (cron only runs after this date)
    @Column({ type: "timestamp", nullable: true })
    startDate!: Date | null;

    // Pending suggestions from previous posts to improve next generation
    @Column({ type: "json", nullable: true })
    pendingSuggestions!: {
        seo: string[];
        geo: string[];
        aeo: string[];
        aio: string[];
    } | null;

    // Target country for geo-targeting and cultural adaptation
    @Column({ type: "varchar", nullable: true })
    targetCountry!: string | null;

    // One-to-many relationship with post logs
    @OneToMany(() => AutoPostLogEntity, (log) => log.schedule)
    logs!: AutoPostLogEntity[];
}
