import { Column, Entity, ManyToOne, JoinColumn, OneToMany } from "typeorm";
import { BaseEntity } from "./base-entity";
import { UserEntity } from "./user-entity";
import { SiteAutoPostLogEntity } from "./site-auto-post-log-entity";

export type SitePostFrequency = "5hours" | "daily" | "weekly" | "biweekly" | "monthly";
export type ContentPillar = "educational" | "trend_analysis" | "case_studies" | "tools_tech" | "strategy" | "engagement";
export type EngagementGoal = "clicks" | "shares" | "comments" | "conversions" | "read_time";
export type ContentFormat = "listicle" | "how_to" | "case_study" | "comparison" | "opinion" | "news" | "story" | "data_study";
export type EmotionalTrigger = "curiosity" | "fear" | "desire" | "urgency" | "belonging" | "achievement";
export type VoiceTrait = "authoritative" | "friendly" | "edgy" | "professional" | "casual" | "inspirational";

@Entity()
export class SiteAutoPostScheduleEntity extends BaseEntity {
    @Column({ type: "uuid" })
    userId!: string;

    @ManyToOne(() => UserEntity, (user) => user.siteAutoPostSchedules, { onDelete: "CASCADE" })
    @JoinColumn({ name: "userId" })
    user!: UserEntity;

    @Column({ type: "boolean", default: true })
    isActive!: boolean;

    // Frequency: 5hours (every 5 hours), daily, weekly, biweekly, monthly
    @Column({ type: "varchar", default: "5hours" })
    frequency!: SitePostFrequency;

    // Topics/themes the user wants to write about
    @Column({ type: "text", nullable: true })
    topics!: string | null;

    // Keywords for SEO
    @Column({ type: "simple-array", nullable: true })
    keywords!: string[] | null;

    // Target audience description
    @Column({ type: "text", nullable: true })
    targetAudience!: string | null;

    // Tone of voice: professional, casual, friendly, etc.
    @Column({ type: "varchar", default: "professional" })
    tone!: string;

    // Preferred post length: short, medium, long
    @Column({ type: "varchar", default: "medium" })
    postLength!: string;

    // Language preference (en, pt, etc.)
    @Column({ type: "varchar", default: "pt" })
    language!: string;

    // Next scheduled post date
    @Column({ type: "timestamp", nullable: true })
    nextPostDate!: Date | null;

    // Last post date
    @Column({ type: "timestamp", nullable: true })
    lastPostDate!: Date | null;

    // Posts generated this month
    @Column({ type: "int", default: 0 })
    postsThisMonth!: number;

    // Month/year for tracking (format: "YYYY-MM")
    @Column({ type: "varchar", nullable: true })
    currentMonth!: string | null;

    // Summary of the user content/generated by AI
    @Column({ type: "text", nullable: true })
    contentSummary!: string | null;

    // When the content summary was generated
    @Column({ type: "timestamp", nullable: true })
    contentSummaryGeneratedAt!: Date | null;

    // Preferred time for posting (format: "HH:mm", e.g., "09:00", "14:30")
    @Column({ type: "varchar", length: 5, default: "09:00" })
    preferredTime!: string;

    // When the schedule should start (cron only runs after this date)
    @Column({ type: "timestamp", nullable: true })
    startDate!: Date | null;

    // Target country for geo-targeting and cultural adaptation
    @Column({ type: "varchar", nullable: true })
    targetCountry!: string | null;

    // Categories/tags for the site blog posts
    @Column({ type: "simple-array", nullable: true })
    categories!: string[] | null;

    // Generate bilingual content (en + pt)
    @Column({ type: "boolean", default: true })
    bilingual!: boolean;

    // ==================== NEW FIELDS FOR ENGAGEMENT & BAML ====================

    // Content Pillar System - Rotação de pilares para variedade
    @Column({ type: "varchar", default: "educational" })
    currentPillar!: ContentPillar;

    // Pillar rotation order (customizable)
    @Column({ type: "simple-array", nullable: true, default: "educational,trend_analysis,case_studies,tools_tech,strategy,engagement" })
    pillarRotation!: string[] | null;

    // Engagement Configuration
    @Column({ type: "varchar", default: "conversions" })
    engagementGoal!: EngagementGoal;

    // Content format optimized for engagement goal
    @Column({ type: "varchar", default: "how_to" })
    contentFormat!: ContentFormat;

    // Emotional trigger for content
    @Column({ type: "varchar", default: "desire" })
    emotionalTrigger!: EmotionalTrigger;

    // Voice Personality Configuration
    @Column({ type: "varchar", default: "professional" })
    voiceTrait!: VoiceTrait;

    @Column({ type: "int", default: 3 })
    voiceHumorLevel!: number; // 0-10

    @Column({ type: "int", default: 6 })
    voiceFormality!: number; // 0-10

    @Column({ type: "int", default: 7 })
    voiceEnthusiasm!: number; // 0-10

    @Column({ type: "boolean", default: true })
    voiceUseEmoji!: boolean;

    // Theme Management
    @Column({ type: "simple-array", nullable: true })
    excludedThemes!: string[] | null; // Theme IDs to exclude

    @Column({ type: "simple-array", nullable: true })
    favoriteThemes!: string[] | null; // Theme IDs to prioritize

    // Content Hash History (used themes - stored as JSON)
    @Column({ type: "text", nullable: true })
    usedContentHashes!: string | null; // JSON array of used hashes

    // Quality Thresholds
    @Column({ type: "int", default: 75 })
    minEngagementScore!: number; // Minimum score to publish (0-100)

    @Column({ type: "int", default: 70 })
    minSeoScore!: number;

    @Column({ type: "int", default: 70 })
    minGeoScore!: number;

    @Column({ type: "int", default: 70 })
    minAeoScore!: number;

    // Variation Settings
    @Column({ type: "int", default: 3 })
    maxAngleVariations!: number; // How many angle variations to try before changing theme

    // Content History (last 90 days themes for anti-repetition)
    @Column({ type: "text", nullable: true })
    contentHistory!: string | null; // JSON array of {hash, theme, angle, date}

    // Auto-optimization
    @Column({ type: "boolean", default: true })
    autoOptimize!: boolean; // Automatically optimize content based on performance

    @Column({ type: "varchar", nullable: true })
    bestPerformingPillar!: string | null; // Auto-detected best pillar

    // One-to-many relationship with post logs
    @OneToMany(() => SiteAutoPostLogEntity, (log) => log.schedule)
    logs!: SiteAutoPostLogEntity[];

    // ==================== HELPER METHODS ====================

    /**
     * Get the next pillar in rotation
     */
    getNextPillar(): ContentPillar {
        const rotation = this.pillarRotation || ["educational", "trend_analysis", "case_studies", "tools_tech", "strategy", "engagement"];
        const currentIndex = rotation.indexOf(this.currentPillar);
        const nextIndex = (currentIndex + 1) % rotation.length;
        return rotation[nextIndex] as ContentPillar;
    }

    /**
     * Add a content hash to history
     */
    addContentHash(hash: string, themeId: string, angle: string): void {
        const history = this.getContentHistory();
        history.push({
            hash,
            themeId,
            angle,
            date: new Date().toISOString()
        });
        
        // Keep only last 90 days (approximately 90 entries for daily posts)
        if (history.length > 100) {
            history.shift();
        }
        
        this.contentHistory = JSON.stringify(history);
    }

    /**
     * Get content history as array
     */
    getContentHistory(): Array<{hash: string; themeId: string; angle: string; date: string}> {
        if (!this.contentHistory) return [];
        try {
            return JSON.parse(this.contentHistory);
        } catch {
            return [];
        }
    }

    /**
     * Check if a hash has been used
     */
    hasUsedHash(hash: string): boolean {
        const history = this.getContentHistory();
        return history.some(h => h.hash === hash);
    }

    /**
     * Get voice configuration object
     */
    getVoiceConfig() {
        return {
            trait: this.voiceTrait,
            humorLevel: this.voiceHumorLevel,
            formality: this.voiceFormality,
            enthusiasm: this.voiceEnthusiasm,
            useEmoji: this.voiceUseEmoji
        };
    }

    /**
     * Get engagement configuration
     */
    getEngagementConfig() {
        return {
            goal: this.engagementGoal,
            format: this.contentFormat,
            trigger: this.emotionalTrigger
        };
    }
}
